### ISSUE TITLE
First letter "white"

### ISSUE THREAD

**Issue by Houbsi** [daylerees/material-peacock#1]
https://infinit.io/_/vf9xHqp

`
    Route::group(['prefix' => 'clients'], function(){
        Route::get('/', ['as' => 'clients.index', 'uses' => 'TKdeController@index']);
        Route::get('/{id}', ['as' => 'clients.show', 'uses' => 'TKdeController@show']);
        Route::post('/create', ['as' => 'clients.store', 'uses' => 'TKdeController@store']);
        Route::get('/{id}/orders', ['as' => 'clients.show.orders', 'uses' => 'TKdeController@showOrders']);
    });`

a bit of weird colouring

**Comment by daylerees** [comment]
Hey @Houbsi , it looks more like your parser might be acting strange there. This is what I have:

http://dayle.io/17OpI
