### ISSUE TITLE
Html colors are broken in PHPStorm2016.1

### ISSUE THREAD

**Issue by freekmurze** [daylerees/material-peacock#16]
Just upgraded to PHPStorm2016.1

This is how blade views look like:
![screen shot 2016-03-22 at 11 54 58](https://cloud.githubusercontent.com/assets/483853/13949399/0e87fa90-f025-11e5-9e78-d3e9a7fd93c3.png)

Funky.

**Comment by gmsantos** [comment]
+1 here too

**Comment by daylerees** [comment]
Hey guys. I'm getting the same thing since updating to the latest PHPStorm version. So I think they have changed either the theme support, or the HTML parser. I'll take a look at this tonight.

**Comment by freekmurze** [comment]
Thanks, greatly appreciated! :+1:

**Comment by daylerees** [comment]
What worries me about this one is that it seems a little conditional. I have a work laptop and a personal laptop, both have the same (latest) version of PHPStorm, and this only happens on my personal laptop.

**Comment by freekmurze** [comment]
Mmmm, so it's probable that a PhpStorm setting is causing problems.

fyi I see this problem on both my work and home machine. I'll try to play with some settings to try to fix this.

Will report back when I found something.

**Comment by daylerees** [comment]
Thanks mate! I'll do the same.

**Comment by freekmurze** [comment]
Updating the Material Theme UI plugin to v0.1.8 solved the problem on my home computer. Will try it on my work computer tomorrow.

**Comment by fwartner** [comment]
Great!

**Comment by freekmurze** [comment]
Unfortunately the problem persists on my work machine...

**Comment by nicholasruunu** [comment]
It's pretty easy to fix through preferences.
Go to `Editor / Color & Fonts / Language Defaults`
And change `Markup / Tag` background to `#171E22`

Go to HTML and if you still see some white background click through and change them too.

**Comment by freekmurze** [comment]
I can confirm that this does indeed solve the problem. It would be nice if the theme would take care of this out of the box. (Not 100% sure if the error is in the theme or some weird plugin 😄 )

**Comment by daylerees** [comment]
I'll make a reminder to fix this later today. Thanks guys.
