### ISSUE TITLE
Theme not coming up in list

### ISSUE THREAD

**Issue by gino** [daylerees/material-peacock#17]
Hello,

I am on Windows and I tried to install the Material Peacock theme. I placed the .icls in the correct folder, path:
**C:\Users\<user>\.PhpStorm2016.3\config\colors**

But it isn't coming up in the list when I try to activate it:
![It isn't in the list](https://i.gyazo.com/6efac96fb3f23bda0f4b28a84f771ae3.png)

I already restarted PHPStorm and rebooted my pc aswell.. still nothing. 😞 

Could someone please help me?

**Comment by AnasMK** [comment]
how did you solve this problem?
