### ISSUE TITLE
JavaScript variables are a bit too dark

### ISSUE THREAD

**Issue by freekmurze** [daylerees/material-peacock#3]
Imho for better readability the purple used for JavaScript variables should be a bit lighter

![screen shot 2016-01-24 at 20 00 43](https://cloud.githubusercontent.com/assets/483853/12538242/2e96b56a-c2d5-11e5-9ed5-1053b176f73f.jpg)

**Comment by daylerees** [comment]
Yep, I imagine we'll find a few of these. Easy to fix. Thanks for the report. Will patch soon!

**Comment by daylerees** [comment]
Pull the latest version and you'll find JS looks a lot better. Thanks for reporting this mate!

**Comment by freekmurze** [comment]
👌
