### ISSUE TITLE
Same color for different function references

### ISSUE THREAD

**Issue by snarexx** [daylerees/material-peacock#4]
In a switch case "function" "switch" , "strtolower" "case" "return" break" they are all same color.
I am not quite sure how they should be colored actually but I think at least they must have minor color differences.
![ekran resmi 2016-01-24 22 34 40](https://cloud.githubusercontent.com/assets/365943/12538744/734bb74a-c2ea-11e5-80f4-b3bb6eb9de03.png)

**Comment by daylerees** [comment]
Ah yep. Lemme see if I can colour the native functions. If they were orange, the problem would be solved.

**Comment by daylerees** [comment]
Pull down the latest version and let me know how it looks? :)

**Comment by serhatculhalik-product** [comment]
Unfortunately it didn't work for me.
To make sure I have the latest, I deleted and reinstalled.

**Comment by daylerees** [comment]
Really? You can see the changeset here.

https://github.com/daylerees/material-peacock/commit/b4b2e8bbdea1e6a38f59f7a83dda5db5902bb363

**Comment by serhatculhalik-product** [comment]
I think in addition to PHP_FUNCTION_CALL you must change "Predefined Symbols" inside "Identifiers"
PHP_FUNCTION_CALL changes color of foo(); inside a function.

**Comment by daylerees** [comment]
Ah I'll take a look soon, just stepped away from my editor. :) Thanks for reporting mate!

**Comment by serhatculhalik-product** [comment]
#6 Fixes but may need a little bit more "touch". Even any other color rather than "orange" can be better. Ayway we gotta follow material design color scheme I think.
