### ISSUE TITLE
Swiggly line

### ISSUE THREAD

**Issue by lstables** [daylerees/material-peacock#5]
There seems to be an issue with the the red swiggly line 

![](http://i.imgur.com/4wrHJ1a.png)

**Comment by daylerees** [comment]
What's the problem? :) That's a PHPStorm feature.

**Comment by lstables** [comment]
Not sure, not seen this before! When I was using the Facebook theme this never shown! Changed to your awesome them and now it does.....

**Comment by daylerees** [comment]
If you imported my settings, you may need to install a Laravel plugin or something. The models use magic accessors for properties, so PHPStorm can't check they exist.

**Comment by lstables** [comment]
Installed Laravel plugin but still same, guess I can live with it, not major. Just thought it may have been a theme issue.

**Comment by daylerees** [comment]
I personally leave it on, but it's probably a setting. You used my settings.jar right?

**Comment by lstables** [comment]
Yes used your settings.

**Comment by daylerees** [comment]
Ah that will be it. Sorry bud. :(
