### ISSUE TITLE
White Background in HTML

### ISSUE THREAD

**Issue by ghost** [daylerees/material-peacock#8]
The background for HTML is white. This looks weird when mixed with PHP. 

![white bg](https://cloud.githubusercontent.com/assets/10871631/12557554/a12e5e32-c38b-11e5-9de6-c87d646b2e31.png)

**Comment by daylerees** [comment]
Damn! I haven't seen that myself, but I'll take a look to be sure mate.

Thanks for reporting.

**Comment by ghost** [comment]
You are welcome mate! Thanks for the nice theme!

**Comment by raphaelsaunier** [comment]
I'm seeing this as well in IntelliJ 15; it seems to be because of the background colour value that's inherited from _'Language Defaults -> Markup -> Tag'_:

![image](https://cloud.githubusercontent.com/assets/170256/12609903/8c7d0608-c4dc-11e5-933d-63556a511aec.png)

**Comment by nicholasruunu** [comment]
Yeah, had the same problem, thanks @raphaelsaunier.

**Comment by daylerees** [comment]
Wanna pull down the latest version? HTML seems to be set to a dark background in mine.

**Comment by serhatculhalik-product** [comment]
@daylerees I tried the latest one but it didn't fix. So I proposed a "fix" in a new PR :) #10

**Comment by daylerees** [comment]
Thanks man. Weird that I can't replicate it.

**Comment by serhatculhalik-product** [comment]
@daylerees Maybe the problem is that I am using PS11 rather than PS10. I think this is the reason why you cannot replicate.
Most probably others, that have the same problem, also have the same version as mine.

**Comment by Kurre** [comment]
FYI
I have this issue with the latest PS11 EAP version (144.3398), but the earlier versions of PS11 worked just fine with peacock theme.

Edit:
#10 by @snarexx fixes this issue for me.

**Comment by nicholasruunu** [comment]
I'm on PHPStorm 10 EAP so I don't think it's it. But maybe it's some minor update problem for 10 that's causing this.

**Comment by stayallive** [comment]
I am seeing the same (in blade files). I am on PhpStorm 11 EAP (27 Jan).

![image](https://cloud.githubusercontent.com/assets/1090754/12646207/ed4e31a8-c5ce-11e5-890d-bcaa32c7b91c.png)

**Comment by daylerees** [comment]
The theme file has the tags set correctly. So I think this might actually be a PHPStorm 11 bug. I wonder if it might be worth reporting it to JetBrains?

**Comment by serhatculhalik-product** [comment]
@nicholasruunu says he has PS10 and he has been having the same problem.
https://github.com/daylerees/material-peacock/issues/8#issuecomment-176175771
@daylerees I am not sure if this is something needs to be reported. Maybe the best way is to install PS10 on a VM and try :)

**Comment by daylerees** [comment]
@nicholasruunu @snarexx  Nick, I wonder if it's to do with the EAP builds. I've been unable to replicate on 10 (final) across a few OS's. I've checked the value of the tags using the UI theme editor, and the values are correct for 10, so I can't change them really.

**Comment by nicholasruunu** [comment]
@daylerees Yeah, definitely seems like something happened after PS10 stable.

**Comment by serhatculhalik-product** [comment]
In my PR #10 tag parameters are set as NULL as in this code. This code is generated automatically by PS11EAP

```
<option name="DEFAULT_TAG">
      <value />
 </option>
```

This **DEFAULT_TAG** doesn't exist in your existing stable icls file. It appeared after I generated automatically with PS11EAP
Before this value, the foreground color used to be **inherited** from some other DEFAULT colors.

So that maybe "DEFAULT_TAG" is presented in PS11EAP or it doesn't exist in your existing stable icls file.

Also it may have a relation with this feature https://www.jetbrains.com/phpstorm/help/wrapping-a-tag-example-of-applying-surround-live-templates.html . When a tag is wrapped the inside it becomes white.

I am not sure now I am totally confused lol :)
