### ISSUE TITLE
Change Weak Warning Color

### ISSUE THREAD

**Issue by abhimanyu003** [daylerees/material-peacock#9]
Please change "Weak Warning" color to something else, it looks like red and appears as real warning :)

![](http://i.imgur.com/o7r8zCj.png)

**Comment by daylerees** [comment]
Ah I lightened the red on the error, so I can see why it might seem this way. This is easy to solve. Thanks for reporting. :)

**Comment by daylerees** [comment]
Fixed this in the latest version. Thanks for the report. :)

**Comment by abhimanyu003** [comment]
Thanks :)
